"""Shared run-book for the staged framework CLI.

A *research run* is one directory under ``reports/research/`` that flows through the four
stages; each stage reads the previous one's artifact from it and writes its own. This module
holds the run directory + the terminal UX (a stage banner, and the exact NEXT command to run,
with the run directory already filled in, so the operator never has to guess what to type).

Deliberately strategy-agnostic: it moves files and prints text, nothing else.
"""

from __future__ import annotations

import contextlib
import json
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from core.paths import REPO_ROOT

from research.stages import lineage

# Render umlauts correctly on UTF-8 terminals (the Windows 11 default) instead of a cp1252 crash.
with contextlib.suppress(Exception):  # pragma: no cover - stream may not support reconfigure
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

_REPO_ROOT = REPO_ROOT
RESEARCH_ROOT = _REPO_ROOT / "reports" / "research"
TOTAL_STAGES = 4

# Only used for runs that predate the manifest (#3); every new run records its own config.
DEFAULT_STUDY_CONFIG = Path("research/config/robustness.py")


@dataclass
class RunDir:
    """One framework run's directory: where each stage reads and writes its artifacts.

    Reading an upstream artifact goes through :meth:`require`, which verifies by CONTENT that the
    file is what its producing stage actually wrote (#31). Writing goes through :meth:`stage`,
    which stages the outputs and publishes them atomically with a manifest.
    """

    path: Path
    allow_legacy: bool = False  # tolerate runs that predate lineage; never deployable
    _verified: lineage.VerifiedInputs = field(default_factory=lineage.VerifiedInputs)
    # Captured when the stage process starts -- i.e. when its work begins, not when it publishes.
    # A stage that ran for hours must be judged by the code it actually imported.
    # Resolved late (not `default_factory=lineage.git_state`) so it is the same callable the
    # writer consults at publication time -- otherwise the two could disagree by construction.
    _git: dict[str, str] = field(default_factory=lambda: lineage.git_state())

    @classmethod
    def create(cls, *, allow_legacy: bool = False) -> RunDir:
        p = RESEARCH_ROOT / f"run_{datetime.now():%Y%m%d_%H%M}"
        p.mkdir(parents=True, exist_ok=True)
        return cls(p, allow_legacy=allow_legacy)

    @classmethod
    def open(cls, path: str | Path, *, allow_legacy: bool = False) -> RunDir:
        p = Path(path)
        if not p.is_dir():
            raise SystemExit(f"run directory not found: {p}")
        return cls(p, allow_legacy=allow_legacy)

    def file(self, name: str) -> Path:
        return self.path / name

    def require(self, name: str, produced_by: str) -> Path:
        """The artifact ``name``, verified against the lineage of the stage that wrote it.

        This is the gate. Existence alone is not enough: the file's content hash must match what
        the producing stage recorded, and that stage's other outputs must be intact too. An
        artifact regenerated by a re-run of an earlier stage therefore fails here, instead of
        being silently combined with results computed from the previous version.
        """
        digest = lineage.verify_artifact(
            self.path, name, produced_by, allow_legacy=self.allow_legacy
        )
        self._verified.add(name, digest)
        return self.file(name)

    def verified_upstream(self) -> dict[str, str]:
        """Hashes of everything read through :meth:`require`, for this stage's own manifest."""
        return dict(self._verified.digests)

    def stage(
        self,
        name: str,
        *,
        argv: dict[str, Any] | None = None,
        seeds: dict[str, Any] | None = None,
        inputs: dict[str, Any] | None = None,
        semantics: dict[str, Any] | None = None,
        git: dict[str, str] | None = None,
    ) -> lineage.StageWriter:
        """Open a stage for writing: staged outputs, atomic publish, manifest written last.

        ``git`` overrides the captured state for a stage whose results were computed by another
        process -- an ingested study belongs to the code that produced it, not to this checkout.
        """
        writer = lineage.StageWriter(
            self.path,
            name,
            run_id=self.run_id(),
            argv=argv,
            seeds=seeds,
            inputs=inputs,
            semantics=semantics,
            git=git if git is not None else self._git,
            check_git=git is None,  # a foreign revision cannot drift against this process
        )
        for artifact, digest in self._verified.digests.items():
            writer.record_upstream(artifact, digest)
        return writer

    def run_id(self) -> str:
        """The run's immutable id, minted by the first stage and carried by the rest."""
        for stage_name in lineage.STAGE_ORDER:
            m = lineage.read_manifest(self.path, stage_name)
            if m is not None:
                return m.run_id
        return lineage.new_run_id()

    def assert_deployable(self, *, ignore: str | None = None) -> None:
        """Refuse to call this run deployable unless every prior stage's lineage verifies.

        ``ignore`` excludes the stage being recomputed right now: a verdict must be judged on its
        prerequisites, not on the output it is in the middle of replacing.
        """
        lineage.assert_deployable(self.path, allow_legacy=self.allow_legacy, ignore=ignore)

    def save_json(self, name: str, obj: dict[str, Any]) -> Path:
        f = self.file(name)
        f.write_text(json.dumps(obj, indent=2), encoding="utf-8")
        return f

    def load_json(self, name: str) -> dict[str, Any]:
        return dict(json.loads(self.file(name).read_text(encoding="utf-8")))

    def study_config(self, override: Path | None = None) -> Path:
        """The study config this run was started with (#3).

        ``override`` wins when given explicitly on the command line; otherwise the path Stage 1
        recorded in the run manifest is used, and only a run predating the manifest falls back to
        the repo default. Without this a run started from one config could be finished with
        another's instruments, account profile and variation definitions -- silently.
        """
        if override is not None:
            return override
        manifest = self.file("run_manifest.json")
        if manifest.exists():
            recorded = self.load_json("run_manifest.json").get("config")
            if recorded:
                return Path(str(recorded))
        return DEFAULT_STUDY_CONFIG


def banner(step: int, title: str, run: RunDir) -> None:
    """Print the stage header (which stage, its question, which run directory)."""
    line = "=" * 72
    print(f"\n{line}\n  STUFE {step}/{TOTAL_STAGES} - {title}\n  Lauf: {run.path}\n{line}")


def cmd(module: str, *args: str) -> str:
    """The exact shell command that starts stage ``module`` with ``args``."""
    tail = (" " + " ".join(args)) if args else ""
    return f"uv run python -m research.stages.{module}{tail}"


def next_step(command: str, prompt: str) -> None:
    """Print the exact next command to run (with the run dir already filled in)."""
    line = "-" * 72
    print(f"\n{line}\n  NAECHSTER SCHRITT - {prompt}:\n\n    {command}\n{line}")


def finished(prompt: str = "Framework-Lauf komplett - Portfolio steht.") -> None:
    print(f"\n{'-' * 72}\n  [OK] {prompt}\n{'-' * 72}")
